[build-system]
requires = ["flit_core >=4,<5"]
build-backend = "flit_core.buildapi"

[project]
name = "stdlibs"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version", "description"]
authors = [
    {name="Amethyst Reese", email="amy@n7.gg"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Utilities",
    "Typing :: Typed",
]
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "attribution",
    "build>=1",
    "black>=25,<27",
    "coverage",
    "fissix",
    "flake8",
    "flit>=4",
    "mypy",
    "packaging",
    "sphinx",
    "sphinx-mdinclude",
    "toml",
    "ufmt",
]

[project.urls]
Homepage = "https://stdlibs.omnilib.dev"
Documentation = "https://stdlibs.omnilib.dev/en/latest/"
Github = "https://github.com/omnilib/stdlibs"

[tool.flit.sdist]
exclude = [
    ".github/",
]

[tool.attribution]
name = "stdlibs"
package = "stdlibs"
ignored_authors = ["dependabot"]
version_file = true
signed_tags = true

[tool.coverage.run]
branch = true
include = ["stdlibs/*"]
omit = ["stdlibs/tests/*"]

[tool.coverage.report]
fail_under = 100
precision = 1
show_missing = true
skip_covered = true
